### ISSUE TITLE
Example of adding a nstandard to multiple libraries

### ISSUE THREAD

**Issue by stephendv1** [iriusrisk/iriusrisktoolkitui#27]
In the document page: https://github.com/iriusrisk/iriusrisktoolkitui/blob/master/documentation/Add_standard_to_libraries.md
We need an example of how to do this with a typical use case:
1. I have my own internal standard called:  ACME Security Standard.
2. Within ACME Security Standard, there is a requirement: 1.1 Encrypt data in transit
3. I want to map that requirement from that standard to at least 3 different controls in 3 different default libraries

Show the steps necessary to do that.  How do I edit the CSV file, where do I put the standard and where do I put the control refs? etc.

**Comment by areyes-cs** [comment]
Sure, I'll do it

**Comment by areyes-cs** [comment]
Done
